import 'package:jobsque/01_model/03_employee_model/employee_model.dart';
import 'package:jobsque/01_model/05_job_model/job_model.dart';
import 'package:jobsque/02_view/04_utilities/res/assets.dart';
import 'package:jobsque/02_view/04_utilities/res/strings.dart';

import '../../../01_model/02_country_model/country_model.dart';

class AppConstants {
  static List<CountryModel> countries = List.generate(
    13,
    (index) => CountryModel(
      id: index+1,
      countryName: AppStrings.countryNames[index],
      flag: AppAssets.countryFlags[index],
    ),
  );

  static List<EmployeeModel> employees = [
    EmployeeModel(
      id: 1,
      name: 'Dimas Adi Saputro',
      jobDegree: 'Senior',
      jobTitle: 'UI/UX Designer',
      workCompany: 'Twitter',
      workDuring: 5,
      photo: AppAssets.countryFlags[6],
    ),
    EmployeeModel(
      id: 2,
      name: 'Syahrul Ramadhani',
      jobDegree: 'Senior',
      jobTitle: 'UI/UX Designer',
      workCompany: 'Twitter',
      workDuring: 5,
      photo: AppAssets.countryFlags[1],
    ),
    EmployeeModel(
      id: 3,
      name: 'Farrel Daniswara',
      jobDegree: 'Senior',
      jobTitle: 'UI/UX Designer',
      workCompany: 'Twitter',
      workDuring: 4,
      photo: AppAssets.countryFlags[2],
    ),
    EmployeeModel(
      id: 4,
      name: 'Azzahra Farrelika',
      jobDegree: '',
      jobTitle: 'UI/UX Designer',
      workCompany: 'Twitter',
      workDuring: 4,
      photo: AppAssets.countryFlags[3],
    ),
    EmployeeModel(
      id: 5,
      name: 'Ferdi Saputra',
      jobDegree: '',
      jobTitle: 'UI/UX Designer',
      workCompany: 'Twitter',
      workDuring: 5,
      photo: AppAssets.countryFlags[4],
    ),
    EmployeeModel(
      id: 6,
      name: 'Dimas Adi Saputro',
      jobDegree: 'Senior',
      jobTitle: 'UI/UX Designer',
      workCompany: 'Twitter',
      workDuring: 5,
      photo: AppAssets.countryFlags[5],
    ),
  ];

  static List<JobModel> suggestedJobs =[
    JobModel(
      id: 0,
      photo: AppAssets.twitterLogo,
      title: AppStrings.suggestedJobsTitle[0],
      minSalary: '12K',
      maxSalary: '15K',
      types: AppStrings.suggestedJobsTypes,
      company: AppStrings.suggestedJobsCompanies[0],
      country: AppStrings.suggestedJobsCountries[0],
      city: 'Indonesia',
      description: AppStrings.applyJobDescriptionSubTitle,
      skills: AppStrings.applyJobRequiredSkills,
      aboutCompany: AppStrings.applyJobCompanyAboutCompanySubTitle,
      companyMail: AppStrings.applyJobCompanyEmail,
      companyWebSite: AppStrings.applyJobCompanyWebSite,
    ),
    JobModel(
      id: 1,
      photo: AppAssets.excelLogo,
      title: AppStrings.suggestedJobsTitle[1],
      minSalary: '14K',
      maxSalary: '20K',
      types: AppStrings.suggestedJobsTypes,
      company: AppStrings.suggestedJobsCompanies[1],
      country: AppStrings.suggestedJobsCountries[1],
      city: 'Cairo',
      description: AppStrings.applyJobDescriptionSubTitle,
      skills: AppStrings.applyJobRequiredSkills,
      aboutCompany: AppStrings.applyJobCompanyAboutCompanySubTitle,
      companyMail: AppStrings.applyJobCompanyEmail,
      companyWebSite: AppStrings.applyJobCompanyWebSite,
    ),
    JobModel(
      id: 0,
      photo: AppAssets.twitterLogo,
      title: AppStrings.suggestedJobsTitle[0],
      minSalary: '12K',
      maxSalary: '15K',
      types: AppStrings.suggestedJobsTypes,
      company: AppStrings.suggestedJobsCompanies[0],
      country: AppStrings.suggestedJobsCountries[0],
      city: 'Indonesia',
      description: AppStrings.applyJobDescriptionSubTitle,
      skills: AppStrings.applyJobRequiredSkills,
      aboutCompany: AppStrings.applyJobCompanyAboutCompanySubTitle,
      companyMail: AppStrings.applyJobCompanyEmail,
      companyWebSite: AppStrings.applyJobCompanyWebSite,
    ),
    JobModel(
      id: 1,
      photo: AppAssets.excelLogo,
      title: AppStrings.suggestedJobsTitle[1],
      minSalary: '14K',
      maxSalary: '20K',
      types: AppStrings.suggestedJobsTypes,
      company: AppStrings.suggestedJobsCompanies[1],
      country: AppStrings.suggestedJobsCountries[1],
      city: 'Cairo',
      description: AppStrings.applyJobDescriptionSubTitle,
      skills: AppStrings.applyJobRequiredSkills,
      aboutCompany: AppStrings.applyJobCompanyAboutCompanySubTitle,
      companyMail: AppStrings.applyJobCompanyEmail,
      companyWebSite: AppStrings.applyJobCompanyWebSite,
    ),
    JobModel(
      id: 0,
      photo: AppAssets.twitterLogo,
      title: AppStrings.suggestedJobsTitle[0],
      minSalary: '12K',
      maxSalary: '15K',
      types: AppStrings.suggestedJobsTypes,
      company: AppStrings.suggestedJobsCompanies[0],
      country: AppStrings.suggestedJobsCountries[0],
      city: 'Indonesia',
      description: AppStrings.applyJobDescriptionSubTitle,
      skills: AppStrings.applyJobRequiredSkills,
      aboutCompany: AppStrings.applyJobCompanyAboutCompanySubTitle,
      companyMail: AppStrings.applyJobCompanyEmail,
      companyWebSite: AppStrings.applyJobCompanyWebSite,
    ),
    JobModel(
      id: 1,
      photo: AppAssets.excelLogo,
      title: AppStrings.suggestedJobsTitle[1],
      minSalary: '14K',
      maxSalary: '20K',
      types: AppStrings.suggestedJobsTypes,
      company: AppStrings.suggestedJobsCompanies[1],
      country: AppStrings.suggestedJobsCountries[1],
      city: 'Cairo',
      description: AppStrings.applyJobDescriptionSubTitle,
      skills: AppStrings.applyJobRequiredSkills,
      aboutCompany: AppStrings.applyJobCompanyAboutCompanySubTitle,
      companyMail: AppStrings.applyJobCompanyEmail,
      companyWebSite: AppStrings.applyJobCompanyWebSite,
    ),
    JobModel(
      id: 0,
      photo: AppAssets.twitterLogo,
      title: AppStrings.suggestedJobsTitle[0],
      minSalary: '12K',
      maxSalary: '15K',
      types: AppStrings.suggestedJobsTypes,
      company: AppStrings.suggestedJobsCompanies[0],
      country: AppStrings.suggestedJobsCountries[0],
      city: 'Indonesia',
      description: AppStrings.applyJobDescriptionSubTitle,
      skills: AppStrings.applyJobRequiredSkills,
      aboutCompany: AppStrings.applyJobCompanyAboutCompanySubTitle,
      companyMail: AppStrings.applyJobCompanyEmail,
      companyWebSite: AppStrings.applyJobCompanyWebSite,
    ),
    JobModel(
      id: 1,
      photo: AppAssets.excelLogo,
      title: AppStrings.suggestedJobsTitle[1],
      minSalary: '14K',
      maxSalary: '20K',
      types: AppStrings.suggestedJobsTypes,
      company: AppStrings.suggestedJobsCompanies[1],
      country: AppStrings.suggestedJobsCountries[1],
      city: 'Cairo',
      description: AppStrings.applyJobDescriptionSubTitle,
      skills: AppStrings.applyJobRequiredSkills,
      aboutCompany: AppStrings.applyJobCompanyAboutCompanySubTitle,
      companyMail: AppStrings.applyJobCompanyEmail,
      companyWebSite: AppStrings.applyJobCompanyWebSite,
    ),
  ];

  static const String loginLink = '134.209.132.80/api/auth/login?';
  static const String registerLink ='134.209.132.80/api/auth/register?';
  static const String workTypeLink ='134.209.132.80/api/user/profile/';
}
